output_format: tsv,fasta
run_dijkstra: true
restore_ends: true

pb:
  internal_length_cutoff: 200
  compression_cutoff: 0.6
  path_limit_stretching: 1.3
  path_limit_pressing: 0.7
  max_path_in_dijkstra: 15000
  max_vertex_in_dijkstra: 5000
  long_seq_limit: 400
  pacbio_min_gap_quantity: 2
  contigs_min_gap_quantity: 1

gap_closing:
  queue_limit: 1000000
  iteration_limit: 1000000
  updates_limit: 1000000
  find_shortest_path: false
  restore_mapping: false
  penalty_ratio: 200
  max_ed_proportion: 3 # max_ed = min(ed_upper_bound, max(sequence_length/max_ed_proportion, ed_lower_bound))
  ed_lower_bound: 500
  ed_upper_bound: 2000
  max_gs_states: 120000000

ends_recovering:
  queue_limit: 1000000
  iteration_limit: 1000000
  updates_limit: 1000000
  find_shortest_path: true
  restore_mapping: false
  penalty_ratio: 0.1
  max_ed_proportion: 5 # max_ed = min(ed_upper_bound, max(sequence_length/max_ed_proportion, ed_lower_bound))
  ed_lower_bound: 500
  ed_upper_bound: 2000
  max_restorable_length: 5000